# Phase 2, Day 57: Direct Preference Optimization (DPO)
import torch
import torch.nn.functional as F

print("--- Booting DPO (Direct Preference Optimization) Pipeline ---")

# DPO requires us to compare the current AI (Policy) against a frozen backup of itself (Reference)
# This prevents the AI from catastrophically forgetting grammar while it learns manners.

def calculate_dpo_loss(policy_chosen_logps, policy_rejected_logps, 
                       ref_chosen_logps, ref_rejected_logps, beta=0.1):
    
    # 1. How much does the CURRENT model prefer the good answer over the bad one?
    policy_logratios = policy_chosen_logps - policy_rejected_logps
    
    # 2. How much did the FROZEN OLD model prefer the good answer over the bad one?
    ref_logratios = ref_chosen_logps - ref_rejected_logps
    
    # 3. Calculate the divergence (The DPO Logit)
    # If this number is positive, the AI is learning correctly.
    logits = policy_logratios - ref_logratios
    
    # 4. The Loss Function
    # We use a Log-Sigmoid. Beta controls how much we punish the AI for drifting from the reference.
    loss = -F.logsigmoid(beta * logits)
    
    return loss.mean(), logits.mean()

# Simulating a human preference dataset
# Human told the AI: "Write a polite greeting."
# Chosen = "Hello, how are you?" | Rejected = "What do you want?"

print("Ingesting Human-Preference Dataset [Chosen vs Rejected]...")

# Simulating the log probabilities (LogPs) of those sentences generated by the models
# The frozen reference model was slightly confused.
ref_chosen_logps = torch.tensor([-2.5])
ref_rejected_logps = torch.tensor([-2.1]) 

# The active policy model is starting to learn that politeness is better.
policy_chosen_logps = torch.tensor([-1.2]) 
policy_rejected_logps = torch.tensor([-3.4]) 

print("Executing DPO Mathematical Alignment...")

loss, divergence = calculate_dpo_loss(
    policy_chosen_logps, 
    policy_rejected_logps, 
    ref_chosen_logps, 
    ref_rejected_logps, 
    beta=0.1
)

print(f"\n--- Optimization Diagnostics ---")
print(f"Policy Divergence Margin: {divergence.item():.4f} (Positive = AI is aligning to human intent)")
print(f"Final DPO Gradient Loss:  {loss.item():.4f}")
print("\nStatus: DPO loss successfully computed. AI alignment update ready without relying on PPO.")